<?php
//    MyDMS. Document Management System
//    Copyright (C) 2002-2005  Markus Westphal
//    Copyright (C) 2006-2008 Malcolm Cowe
//    Copyright (C) 2010 Matteo Lucarelli
//
//    This program is free software; you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation; either version 2 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program; if not, write to the Free Software
//    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

$text = array();
$text["accept"] = "Accetta";
$text["access_denied"] = "Accesso negato";
$text["access_inheritance"] = "Permessi ereditari";
$text["access_mode"] = "Permessi";
$text["access_mode_all"] = "Permessi totali";
$text["access_mode_none"] = "Nessun accesso";
$text["access_mode_read"] = "Permesso di lettura";
$text["access_mode_readwrite"] = "Permesso di lettura e scrittura";
$text["account_summary"] = "Dettagli Account";
$text["action_summary"] = "Dettaglio Azioni";
$text["actions"] = "Azioni";
$text["add_access"] = "Aggiungi permesso";
$text["add_doc_reviewer_approver_warning"] = "Nota: i documenti saranno automaticamente distinti come rilasciati se non esiste approvazione o revisione";
$text["add_document_link"] = "Aggiungi collegamento";
$text["add_document"] = "Aggiungi documento";
$text["add_group"] = "Aggiungi nuovo gruppo";
$text["add_link"] = "Crea un collegamento";
$text["add_member"] = "Aggiungi un membro";
$text["add_new_notify"] = "Aggiungi nuova notifica";
$text["add_subfolder"] = "Aggiungi sottocartella";
$text["add_user"] = "Aggiungi nuovo utente";
$text["add"] = "Aggiungi";
$text["admin_tools"] = "Amministrazione";
$text["admin"] = "Amministratore";
$text["all_documents"] = "Tutti i documenti";
$text["all_users"] = "Tutti gli utenti";
$text["already_subscribed"] = "L'oggetto &egrave; gi&agrave; stato sottoscritto";
$text["and"] = "e";
$text["approval_group"] = "Gruppo approvazione";
$text["approval_status"] = "Stato approvazione";
$text["approval_summary"] = "Dettaglio approvazioni";
$text["approval_update_failed"] = "Errore nel modificare lo stato di approvazione";
$text["approve_document_complete_records_updated"] = "Approvazione documento completata e record modificato";
$text["approve_document_complete"] = "Approvazione documento: Completata";
$text["approve_document"] = "Documento approvato";
$text["approvers"] = "Approvatori";
$text["as_approver"] = "come un approvatore";
$text["as_reviewer"] = "come un revisore";
$text["assumed_released"] = "Rilascio Acquisito";
$text["back"] = "Ritorna";
$text["between"] = "tra";
$text["cancel"] = "Annulla";
$text["cannot_approve_pending_review"] = "Il documento &egrave; in corso di revisione. Non pu&ograve; essere sottoposto attualmente ad una approvazione.";
$text["cannot_assign_invalid_state"] = "Non &egrave; possibile modificare le assegnazioni di un documento gi&agrave; in stato finale";
$text["cannot_change_final_states"] = "Attenzione: Non si pu&ograve; modificare lo stato dei documenti rifiutati, scaduti o in lavorazione";
$text["cannot_delete_admin"] = "Impossibile cancellare l'utente amministrativo primario";
$text["cannot_move_root"] = "Impossibile spostare la cartella di root";
$text["cannot_retrieve_approval_snapshot"] = "Impossibile visualizzare lo stato di approvazione per questa versione di documento";
$text["cannot_retrieve_review_snapshot"] = "Impossibile visualizzare lo stato di revisione per questa versione di documento";
$text["cannot_rm_root"] = "Impossibile cancellare la cartella di root";
$text["choose_category"] = "Seleziona";
$text["choose_group"] = "--Seleziona gruppo--";
$text["choose_target_document"] = "Seleziona documento";
$text["choose_target_folder"] = "Seleziona cartella";
$text["choose_user"] = "--Seleziona utente--";
$text["comment_for_current_version"] = "Commento per la versione";
$text["comment"] = "Commento";
$text["confirm_pwd"] = "Conferma Password";
$text["confirm_rm_document"] = "Vuoi veramente eliminare il documento \"[documentname]\"?<br>Attenzione: L'operazione &egrave; irreversibile";
$text["confirm_rm_folder"] = "Vuoi veramente eliminare la cartella \"[foldername]\" e tutto il suo contenuto?<br>Attenzione: L'operazione &egrave; irreversibile";
$text["confirm_rm_version"] = "Vuoi veramente eliminare la versione  [version] del documento \"[documentname]\"?<br>Attenzione: L'operazione &egrave; irreversibile";
$text["content"] = "Cartelle";
$text["continue"] = "Continua";
$text["creation_date"] = "Data creazione";
$text["current_version"] = "Ultima versione";
$text["default_access"] = "Permesso di default";
$text["default_keyword_category_name"] = "Nome";
$text["default_keyword_category"] = "Categoria";
$text["default_keywords"] = "Parole chiave disponibili";
$text["delete"] = "Cancella";
$text["details"] = "Dettagli";
$text["details_version"] = "Dettagli versione: [version]";
$text["document_already_locked"] = "Questo documento &egrave; gi&agrave; bloccato";
$text["document_infos"] = "Informazioni documento";
$text["document_is_not_locked"] = "Questo documento non &egrave; bloccato";
$text["document_link_by"] = "Collegato da";
$text["document_link_public"] = "Pubblico";
$text["document_list"] = "Documenti";
$text["document_overview"] = "Descrizione del documento";
$text["document_status"] = "Stato del Documento";
$text["document_title"] = "Documento '[documentname]'";
$text["document_versions"] = "Tutte le versioni";
$text["document"] = "Documento";
$text["documents_in_process"] = "Documenti in lavorazione";
$text["documents_owned_by_user"] = "Documenti posseduti dall'utente";
$text["documents_to_approve"] = "Documenti in attesa della tua approvazione";
$text["documents_to_review"] = "Documenti in attesa della tua revisione";
$text["documents_user_requiring_attention"] = "Tuoi documenti in attesa di revisione o approvazione";
$text["does_not_expire"] = "Nessuna scadenza";
$text["does_not_inherit_access_msg"] = "<a class=\"inheritAccess\" href=\"[inheriturl]\">Imposta permessi ereditari</a>";
$text["download"] = "Scarica";
$text["draft_pending_approval"] = "Bozza in approvazione";
$text["draft_pending_review"] = "Bozza in revisione";
$text["edit_default_keyword_category"] = "Modifica categoria";
$text["edit_default_keywords"] = "Modifica parole chiave";
$text["edit_document_access"] = "Modifica permessi";
$text["edit_document_notify"] = "Lista di notifica file";
$text["edit_document_props_again"] = "Modifica nuovamente il documento";
$text["edit_document_props"] = "Gestione documento";
$text["edit_document"] = "Modifica documento";
$text["edit_existing_access"] = "Gestione permessi";
$text["edit_existing_notify"] = "Gestione lista di notifica";
$text["edit_folder_access"] = "Modifica permessi";
$text["edit_folder_notify"] = "Lista di notifica cartelle";
$text["edit_folder_props_again"] = "Modifica nuovamente la cartella";
$text["edit_folder_props"] = "Gestione Cartella";
$text["edit_folder"] = "Modifica cartella";
$text["edit_group"] = "Modifica gruppo";
$text["edit_personal_default_keywords"] = "Gestione parole chiave personali";
$text["edit_user_details"] = "Gestione dettagli utente";
$text["edit_user"] = "Modifica utente";
$text["edit"] = "modifica";
$text["email_err_group"] = "Errore nell'invio di email a uno o pi&ugrave; membri del gruppo [group]";
$text["email_err_user"] = "Errore nell'invio di email all'utente [user]";
$text["email_sent"] = "Email inviata";
$text["email"] = "Email";
$text["empty_access_list"] = "La lista permessi &egrave; vuota";
$text["empty_notify_list"] = "Nessun record";
$text["error_occured"] = "Si verificato un errore";
$text["exp_date"] = "Data Scadenza";
$text["expired"] = "Scaduto";
$text["expires"] = "Scadenza";
$text["file_info"] = "Informazioni sul file";
$text["file_size"] = "Grandezza";
$text["file"] = "File";
$text["folder_contents"] = "Contenuto cartella";
$text["folder_infos"] = "Informazioni cartella";
$text["folder_notify_again"] = "Modifica nuovamente lista notifica";
$text["folder_overview"] = "Vista generale cartella";
$text["folder_path"] = "Percorso";
$text["folder_title"] = "Cartella '[foldername]'";
$text["folders_and_documents_statistic"] = "Visualizzazione generale";
$text["foldertree"] = "Albero cartella";
$text["from_approval_process"] = "dal processo di approvazione";
$text["from_review_process"] = "dal processo di revisione";
$text["global_default_keywords"] = "Categorie parole chiave globali";
$text["goto"] = "Vai a";
$text["group_already_approved"] = "Un'approvazione &egrave; gi&agrave; stata presentata a nome del gruppo";
$text["group_already_reviewed"] = "Una revisione &egrave; gi&agrave; stata presentata a nome del gruppo";
$text["group_approvers"] = "Gruppo Approvatori";
$text["group_email_sent"] = "Email trasmessa ai membri del gruppo";
$text["group_exists"] = "Il gruppo &egrave; gi&agrave; esistente";
$text["group_management"] = "Amministrazione gruppi";
$text["group_members"] = "Membri del gruppo";
$text["group_reviewers"] = "Gruppo Revisori";
$text["group_unable_to_add"] = "Impossibile aggiungere un gruppo";
$text["group_unable_to_remove"] = "Impossibile rimuovere un gruppo";
$text["group"] = "Gruppo";
$text["groups"] = "Gruppi";
$text["guest_login_disabled"] = "Login ospite &egrave; disabilitato";
$text["guest_login"] = "Login come ospite";
$text["individual_approvers"] = "Approvatori singoli";
$text["individual_reviewers"] = "Revisori singoli";
$text["individuals"] = "Singoli";
$text["inherits_access_msg"] = "E' impostato il permesso ereditario.<p><a class=\"inheritAccess\" href=\"[copyurl]\">Modifica la lista degli accessi ereditati</a><br><a class=\"inheritAccess\" href=\"[emptyurl]\">Riimposta una lista di permessi vuota</a>";
$text["internal_error_exit"] = "Errore interno. Impossibile completare la richiesta. Uscire.";
$text["internal_error"] = "Errore interno";
$text["invalid_access_mode"] = "Permessi non validi";
$text["invalid_action"] = "Azione non valida";
$text["invalid_approval_status"] = "Stato di approvazione non valido";
$text["invalid_create_date_end"] = "Fine data non valida per la creazione di un intervallo temporale";
$text["invalid_create_date_start"] = "Inizio data non valida per la creazione di un intervallo temporale";
$text["invalid_doc_id"] = "ID documento non valido";
$text["invalid_folder_id"] = "ID cartella non valido";
$text["invalid_group_id"] = "ID gruppo non valido";
$text["invalid_link_id"] = "ID di collegamento non valido";
$text["invalid_review_status"] = "Stato revisione non valido";
$text["invalid_sequence"] = "Valore di sequenza non valido";
$text["invalid_status"] = "Stato del documento non valido";
$text["invalid_target_doc_id"] = "ID documento selezionato non valido";
$text["invalid_target_folder"] = "ID cartella selezionata non valido";
$text["invalid_user_id"] = "ID utente non valido";
$text["invalid_version"] = "Versione documento non valida";
$text["is_admin"] = "Amministratore privilegiato";
$text["js_no_approval_group"] = "Si prega di selezionare un gruppo di approvazione";
$text["js_no_approval_status"] = "Si prega di selezionare lo stato di approvazione";
$text["js_no_comment"] = "Non ci sono commenti";
$text["js_no_email"] = "Scrivi nel tuo indirizzo di Email";
$text["js_no_file"] = "Per favore seleziona un file";
$text["js_no_keywords"] = "Specifica alcune parole chiave";
$text["js_no_login"] = "Il campo ID utente é necessario";
$text["js_no_name"] = "Il nome é necessario";
$text["js_no_override_status"] = "E' necessario selezionare un nuovo stato";
$text["js_no_pwd"] = "La password è necessaria";
$text["js_no_query"] = "Scrivi nella query";
$text["js_no_review_group"] = "Per favore seleziona un gruppo di revisori";
$text["js_no_review_status"] = "Per favore seleziona lo stato di revisione";
$text["js_pwd_not_conf"] = "Password e passwords-di conferma non corrispondono";
$text["js_select_user_or_group"] = "Selezionare almeno un utente o un gruppo";
$text["js_select_user"] = "Per favore seleziona un utente";
$text["keyword_exists"] = "Parola chiave gi&agrave; presente";
$text["keywords"] = "Parole chiave";
$text["language"] = "Lingua";
$text["last_update"] = "Ultima modifica";
$text["last_updated_by"] = "Ultima modifica eseguita da";
$text["latest_version"] = "Ultima versione";
$text["linked_documents"] = "Documenti collegati";
$text["local_file"] = "File locale";
$text["lock_document"] = "Blocca";
$text["lock_message"] = "Questo documento &egrave; bloccato da <a href=\"mailto:[email]\">[username]</a>. Solo gli utenti autorizzati possono sbloccare questo documento.";
$text["lock_status"] = "Stato";
$text["logged_in_as"] = "Loggato";
$text["login_error_text"] = "Errore nel login. ID utente o passord errati.";
$text["login_error_title"] = "Errore di login";
$text["login_not_found"] = "Questo nome utente non esiste";
$text["login_not_given"] = "Non &egrave; stato inserito il nome utente";
$text["login_ok"] = "Login eseguito";
$text["login"] = "Login";
$text["logout"] = "Logout";
$text["mime_type"] = "Mime-Type";
$text["move_document"] = "Sposta documento";
$text["move_folder"] = "Sposta cartella";
$text["move"] = "Sposta";
$text["my_account"] = "Account personale";
$text["my_documents"] = "Documenti personali";
$text["name"] = "Nome";
$text["new_default_keyword_category"] = "Aggiungi categoria";
$text["new_default_keywords"] = "Aggiungi parole chiave";
$text["new_user_image"] = "Nuova immagine";
$text["no_action_required"] = "n/a";
$text["no_action"] = "Non &egrave; richiesto alcun intervento";
$text["no_active_user_docs"] = "Non ci sono attualmente tuoi documenti in attesa di revisione o approvazione .";
$text["no_approvers"] = "Nessun approvatore assegnato.";
$text["no_default_keywords"] = "Nessuna parola chiave disponibile";
$text["no_documents"] = "Nessun documento";
$text["no_group_members"] = "Questo gruppo non ha membri";
$text["no_groups"] = "Nessun gruppo";
$text["no_previous_versions"] = "Nessun'altra versione trovata";
$text["no_reviewers"] = "Nessun revisore assegnato.";
$text["no_subfolders"] = "Nessuna sottocartella";
$text["no_update_cause_locked"] = "Non &egrave; quindi possible aggiornarlo.";
$text["no_user_image"] = "Nessuna immagine trovata";
$text["no"] = "No";
$text["notify_subject"] = "Documenti nuovi o scaduti nel tuo archivio";
$text["obsolete"] = "Obsoleto";
$text["old_folder"] = "cartella vecchia";
$text["only_jpg_user_images"] = "Possono essere utilizzate solo immagini di tipo jpeg";
$text["op_finished"] = "fatto";
$text["override_content_status"] = "Modifica stato";
$text["overview"] = "Visualizzazione generale";
$text["owner"] = "Proprietario";
$text["password"] = "Password";
$text["pending_approval"] = "Documenti in attesa di approvazione";
$text["pending_review"] = "Documenti in attesa di revisione";
$text["personal_default_keywords"] = "Parole chiave personali";
$text["previous_versions"] = "Versioni precedenti";
$text["rejected"] = "Rifiutato";
$text["released"] = "Rilasciato";
$text["remove_document_link"] = "Rimuovi collegamento";
$text["remove_member"] = "Rimuovi membro";
$text["removed_approver"] = "Rimosso dalla lista degli approvatori.";
$text["removed_reviewer"] = "Rimosso dalla lista dei revisori.";
$text["review_document"] = "Revisione Documento";
$text["review_group"] = "Gruppo revisori";
$text["review_status"] = "Stato revisioni";
$text["review_summary"] = "Dettaglio revisioni";
$text["review_update_failed"] = "Errore nella variazione della revisione. Aggiornamento fallito.";
$text["reviewer_added"] = "aggiunta come revisione";
$text["reviewer_already_assigned"] = "gi&agrave; &egrave; assegnato come revisore";
$text["reviewer_already_removed"] = "gi&agrave; rimosso dal processo di revisione oppure gi&agrave; inserito come revisione";
$text["reviewer_removed"] = "rimosso dal processo di revisione";
$text["reviewers"] = "Revisori";
$text["rm_default_keyword_category"] = "Cancella categoria";
$text["rm_default_keywords"] = "Cancella parole chiave";
$text["rm_document"] = "Rimuovi documento";
$text["rm_folder"] = "Rimuovi cartella";
$text["rm_group"] = "Rimuovi questo gruppo";
$text["rm_user"] = "Rimuovi questo utente";
$text["rm_version"] = "Rimuovi versione";
$text["root_folder"] = "Cartella Principale";
$text["save"] = "Salva";
$text["search_in_all"] = "tutte le cattelle";
$text["search_in_current"] = "solo in questa ([foldername]) incluse le sottocartelle";
$text["search_in"] = "Cerca in";
$text["search_mode_and"] = "tutte le parole";
$text["search_mode_or"] = "almeno una parola";
$text["search_mode"] = "Modo";
$text["search_no_results"] = "Non ci sono documenti che contengano la vostra ricerca";
$text["search_query"] = "Cerca per";
$text["search_report"] = "Trovati [count] documenti";
$text["search_result_pending_approval"] = "stato 'in attesa di approvazione'";
$text["search_result_pending_review"] = "stato 'in attesa di revisione'";
$text["search_results_access_filtered"] = "La ricerca pu&ograve; produrre contenuti il cui accesso &egrave; negato.";
$text["search_results"] = "Risultato ricerca";
$text["search_time"] = "Tempo trascorso: [time] sec.";
$text["search"] = "Cerca";
$text["select_one"] = "Seleziona uno";
$text["selected_document"] = "Seleziona documento";
$text["selected_folder"] = "Seleziona cartella";
$text["selection"] = "Selezione";
$text["seq_after"] = "Dopo \"[prevname]\"";
$text["seq_end"] = "Alla fine";
$text["seq_keep"] = "Mantene Posizione";
$text["seq_start"] = "Prima posizione";
$text["sequence"] = "Posizione";
$text["set_default_access"] = "Conferma permessi di default";
$text["set_expiry"] = "Regola la scadenza";
$text["set_owner"] = "Conferma proprietario";
$text["set_reviewers_approvers"] = "Assegnare i revisori e gli approvatori";
$text["show_all_versions"] = "Mostra tutte le revisioni";
$text["show_current_versions"] = "Mostra solo la versione corrente";
$text["start"] = "Avvia";
$text["status_approval_rejected"] = "Bozza rifiutata";
$text["status_approved"] = "Approvato";
$text["status_approver_removed"] = "Approvatore rimosso dal processo";
$text["status_changed_by"] = "Stato cambiato da";
$text["status_not_approved"] = "Non ancora approvato";
$text["status_not_reviewed"] = "Non ancora revisionato";
$text["status_reviewed"] = "Revisionato";
$text["status_reviewer_rejected"] = "Bozza rifiutata";
$text["status_reviewer_removed"] = "Revisore rimosso dal processo";
$text["status_unknown"] = "Sconosciuto";
$text["status"] = "Stato";
$text["subfolder_list"] = "Sottocartelle";
$text["submit_approval"] = "Approvazione documento";
$text["submit_login"] = "Login";
$text["submit_review"] = "Revisione documento";
$text["theme"] = "Tema";
$text["unable_to_add"] = "Impossibile aggiungere";
$text["unable_to_remove"] = "Impossibile rimuovere";
$text["under_folder"] = "Nella cartella";
$text["unknown_command"] = "Commando non riconosciuto.";
$text["unknown_group"] = "ID gruppo sconosciuto";
$text["unknown_keyword_category"] = "Categoria sconosciuta";
$text["unknown_owner"] = "ID proprietario sconosciuto";
$text["unknown_user"] = "ID utente sconosciuto";
$text["unlock_cause_access_mode_all"] = "Puoi ancora aggiornarlo, perch&egrave; hai il permesso  \"all\". Il blocco sar&agrave; rimosso automaticamente.";
$text["unlock_cause_locking_user"] = "Puoi ancora aggiornarlo, perch&egrave; sei l'utente che ha eseguito il blocco. Il blocco sar&agrave; rimosso automaticamente.";
$text["unlock_document"] = "Sblocca";
$text["update_approvers"] = "Aggiornamento lista approvatori";
$text["update_document"] = "Aggiorna";
$text["update_info"] = "Aggiorna informazioni";
$text["update_locked_msg"] = "Questo documento &egrave; bloccato.";
$text["update_reviewers"] = "Aggiornamento lista revisori";
$text["update"] = "Aggiorna";
$text["updated_by"] = "Aggiornato da";
$text["upload_date"] = "Data Upload";
$text["uploaded_by"] = "Caricato da";
$text["uploaded"] = "Uploaded";
$text["uploading_failed"] = "Upload fallito. Sei pregato di contattare l'amministratore.";
$text["use_default_keywords"] = "Usa le parole chiave predefinite";
$text["user_exists"] = "Utente esistente";
$text["user_image"] = "Immagine";
$text["user_info"] = "Informazioni utente";
$text["user_list"] = "Lista utenti";
$text["user_login"] = "ID utente";
$text["user_management"] = "Amministrazione utenti";
$text["user_name"] = "Nome e Cognome";
$text["user"] = "Utente";
$text["users"] = "Utenti";
$text["version_info"] = "Informazioni versione";
$text["version_under_approval"] = "Versione in fase di approvazione";
$text["version_under_review"] = "Versione in fase di revisione";
$text["version"] = "Versione";
$text["view_document"] = "Visualizza documento";
$text["view_online"] = "Visualizza";
$text["warning"] = "Attenzione";
$text["wrong_pwd"] = "Password errata. Riprova.";
$text["yes"] = "Si";

// new
$text["documents"] = "Documenti";
$text["folders"] = "Cartelle";
$text["no_folders"] = "Nessuna cartella";
$text["notification_summary"] = "Sommario notifiche";
$text["all_pages"] = "Tutte";
$text["results_page"] = "Pagina dei risultati";
$text["sign_out"] = "Esci";
$text["signed_in_as"] = "Utente";
$text["assign_reviewers"] = "Assegna Revisori";
$text["assign_approvers"] = "Assegna Approvatori";
$text["override_status"] = "Modifica lo Stato";
$text["change_status"] = "Modifica lo Stato";
$text["change_assignments"] = "Modifica le Assegnazioni";
$text["no_user_docs"] = "Non ci sono attualmente tuoi documenti";
$text["disclaimer"] = "Questa &egrave; un'area riservata. L'accesso &egrave; consentito solo al personale autorizzato. Qualunque violazione sar&agrave; perseguita a norma delle leggi italiane ed internazionali.";
$text["error_updating_status"] = "Errore durante la modifica dello stato del documento";
$text["unknown_id"] = "identificativo sconosciuto";
$text["help"] = "Aiuto";

$text["group_approval_summary"] = "Dettaglio approvazioni di gruppo";
$text["group_review_summary"] = "Dettaglio revisioni di gruppo";
$text["documents_locked_by_you"] = "Documenti bloccati da te";

$text["document_renamed_email"] = "Documento rinominato";
$text["folder_renamed_email"] = "Cartella rinominata";
$text["comment_changed_email"] = "Commento cambiato";
$text["document_moved_email"] = "Documento spostato";
$text["folder_moved_email"] = "Cartella spostata";
$text["ownership_changed_email"] = "Proprietario cambiato";
$text["access_permission_changed_email"] = "Permessi cambiati";
$text["expiry_changed_email"] = "Scadenza cambiata";
$text["notify_added_email"] = "Sei stato aggiunto alla lista di notifica";
$text["notify_deleted_email"] = "Sei stato eliminato dalla lista di notifica";
$text["document_updated_email"] = "Documento aggiornato";
$text["document_deleted_email"] = "Documento cancellato";
$text["folder_deleted_email"] = "Cartella cancellata";
$text["version_deleted_email"] = "Versione cancellata";
$text["document_status_changed_email"] = "Modifica stato del documento";
$text["review_request_email"] = "Richiesta di revisione";
$text["approval_request_email"] = "Richiesta di approvazione";
$text["review_deletion_email"] = "Cancellata la richiesta di revisione";
$text["approval_deletion_email"] = "Cancellata la richiesta di approvazione";
$text["new_subfolder_email"] = "Nuova sottocartella";
$text["new_document_email"] = "Nuovo documento";
$text["approval_submit_email"] = "Sottoposta approvazione";
$text["review_submit_email"] = "Sottoposta revisione";
$text["automatic_status_update"] = "Modifica automatica dello stato";
$text["old"] = "Vecchio"; 
$text["new"] = "Nuovo"; 
$text["folder"] = "Cartella"; 

$text["new_file_email"] = "Nuovo file allegato";
$text["removed_file_email"] = "Rimosso file allegato";

$text["document_deleted"] = "Documento rimosso"; 
$text["linked_files"] = "File allegati"; 
$text["invalid_file_id"] = "ID del file non valido";
$text["rm_file"] = "Rimuovi file"; 
$text["confirm_rm_file"] = "Vuoi veramente eliminare il file \"[name]\" del documento \"[documentname]\"?<br>Attenzione: L'operazione &egrave; irreversibile";

$text["backup_tools"] = "Strumenti di backup"; 
$text["versioning_file_creation"] = "Creazione file di versionamento"; 
$text["archive_creation"] = "Creazione archivi"; 
$text["files_deletion"] = "Cancellazione file"; 

$text["versioning_info"] = "Informazioni di versionamento";
$text["versioning_file_creation_warning"] = "Con questa operazione &egrave; possibile creare un file di backup delle informazioni di versionamento dei documenti di una intera cartella. Dopo la creazione ogni file viene salvato nella cartella del relativo documento.";
$text["archive_creation_warning"] = "Con questa operazione &egrave; possibile creare archivi contenenti i file di intere cartelle del DMS. Dopo la creazione l'archivio viene salvato nella cartella dati del server.<br>Attenzione: un archivio creato per uso esterno non &egrave; utilizzabile come backup del server.";
$text["files_deletion_warning"] = "Con questa operazione &egrave; possible cancellare i file di intere cartelle. Dopo la cancellazione le informazioni di versionamento resteranno disponibili."; 

$text["confirm_rm_folder_files"] = "Vuoi davvero rimuovere tutti i file dalla cartella \"[foldername]\" e dalle sue sottocartelle?<br>Attenzione: Questa operazione non pu&ograve; essere annullata.";

$text["files"] = "Files";
$text["storage_size"] = "Dimensione totale";

$text["backup_list"] = "Lista dei backup presenti";
$text["backup_remove"] = "Elimina file di backup";
$text["confirm_rm_backup"] = "Vuoi davvero rimuovere il file \"[arkname]\"?<br>Attenzione: Questa operazione non pu&ograve; essere annullata.";

$text["edit_comment"] = "Modifica il commento";

// new from 1.9
$text["is_hidden"] = "Nascondi dalla lista utenti";
$text["log_management"] = "Amministrazione log file";
$text["confirm_rm_log"] = "Vuoi davvero rimuovere il file di log \"[logname]\"?<br>Attenzione: Questa operazione non pu&ograve; essere annullata.";
$text["include_subdirectories"] = "Includi sottocartelle";
$text["include_documents"] = "Includi documenti";
$text["manager"] = "Manager";
$text["toggle_manager"] = "Manager";

// new from 2.0

$text["calendar"] = "Calendario";
$text["week_view"] = "Vista settimana";
$text["month_view"] = "Vista mese";
$text["year_view"] = "Vista anno";
$text["add_event"] = "Aggiungi evento";
$text["edit_event"] = "Modifica evento";

$text["january"] = "Gennaio";
$text["february"] = "Febbraio";
$text["march"] = "Marzo";
$text["april"] = "Aprile";
$text["may"] = "Maggio";
$text["june"] = "Giugno";
$text["july"] = "Luglio";
$text["august"] = "Agosto";
$text["september"] = "Settembre";
$text["october"] = "Ottobre";
$text["november"] = "Novembre";
$text["december"] = "Dicembre";

$text["sunday"] = "Domenica";
$text["monday"] = "Luned&igrave;";
$text["tuesday"] = "Marted&igrave;";
$text["wednesday"] = "Mercoled&igrave;";
$text["thursday"] = "Gioved&igrave;";
$text["friday"] = "Venerd&igrave;";
$text["saturday"] = "Sabato";

$text["from"] = "Da";
$text["to"] = "A";

$text["event_details"] = "Dettagli evento";
$text["confirm_rm_event"] = "Vuoli davvero rimuovere l'evento \"[name]\"?<br>Attenzione: Questa operazione non pu&ograve; essere annullata.";

$text["dump_creation"] = "Creazione DB dump"; 
$text["dump_creation_warning"] = "Con questa operazione &egrave; possibile creare un file di dump del contenuto del database. Dopo la creazione il file viene salvato nella cartella dati del server.";
$text["dump_list"] = "List dei dump presenti";
$text["dump_remove"] = "Cancella il dump file";
$text["confirm_rm_dump"] = "Vuoi davvero rimuovere il file \"[dumpname]\"?<br>Attenzione: Questa operazione non pu&ograve; essere annullata.";

$text["confirm_rm_user"] = "Vuoi davvero rimuovere l'utente \"[username]\"?<br>Attenzione: Questa operazione non pu&ograve; essere annullata.";
$text["confirm_rm_group"] = "Vuoi davvero rimuovere il gruppo \"[groupname]\"?<br>Attenzione: Questa operazione non pu&ograve; essere annullata.";

$text["human_readable"] = "Archivio per uso esterno"; 

$text["email_header"] = "Questo &egrave; un messaggio automatico inviato dal server DMS"; 
$text["email_footer"] = "Puoi cambiare le tue preferenze utilizzando le funzioni del menu 'Account personale'"; 

$text["add_multiple_files"] = "Aggiungi documenti multipli (il nome del file verr&agrave; usato come nome del documento)";

// new from 2.0.1

$text["max_upload_size"] = "Dimensione massima caricabile per ogni file";

// new from 2.0.2

$text["space_used_on_data_folder"] = "Spazio utilizzato dai dati";
$text["assign_user_property_to"] = "Assegna le propriet&agrave; dell'utente a";

?>
